### ISSUE TITLE
Image doesn't resize on first boot

### ISSUE THREAD

**Issue by bspeice** [hypriot/image-builder-odroid-c2#33]
Leads to plenty of issues. How is firstboot.d supposed to be triggered?

**Comment by StefanScherer** [comment]
We have removed the firstboot service in os-rootfs 2.0.0.

Switch back by setting HYPRIOT_OS_VERSION to v1.2.6

**Comment by bspeice** [comment]
Got it. Is there another way to resize the main partition on boot? Is that something that should go in user-data as part of cloud-init?

**Comment by StefanScherer** [comment]
Maybe https://github.com/hypriot/image-builder-rpi/pull/227 is of help. I moved the

.../files/etc/firstboot.d/10-resize-rootdisk → .../var/lib/cloud/scripts/per-once/resize2fs 

But it turned out that this step is called after some other user-data commands that want to install new packages.

On RPi we finally use the Raspbian reboot trick that resizes the filesystem at a very early stage.

**Comment by trebolcinco** [comment]
Sadly I've dropped back to 3.1 due to resize issue.  Is there any update on its way?  If not, is there a workaround?

**Comment by bspeice** [comment]
The workaround at the moment would be to resize the partition manually after flashing. I'm blocked at the moment because my only C2 is in use, so I don't really have anything to test on. If I get to it, I'll order another soon enough.

Happy to start hacking on this if you'd be able to help me though, the fix shouldn't be terribly difficult.

**Comment by trebolcinco** [comment]
@bspeice I'd be happy to help hack at it with you.

**Comment by bspeice** [comment]
Resolved by merge in #34

**Comment by StefanScherer** [comment]
The SD image for v0.4.1 is now available at https://github.com/hypriot/image-builder-odroid-c2/releases/tag/v0.4.1
